### ISSUE TITLE
Add support for Camtrap DP 1.0

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#2180]
I just released Camtrap DP 1.0: https://github.com/tdwg/camtrap-dp/releases/tag/1.0. @mike-podolskiy90 can this stable release be supported by the IPT? There are a couple of changes compared to the release candidate of Camtrap DP (1.0-rc.1). Here's a summary of what affect the IPT:

- [x] Copy the profile and table schemas to rs.gbif.org (cf. 1.0-rc.1).
  - Changes in the table schemas (new term `deployments.cameraDepth`, deleted term `observations.taxonID` (see below), controlled vocabulary update to `media.captureMethod` and stricter validation for `media.fileMedia`) will be automatically reflected in the IPT.
- [x] The enum for `project.captureMethod` has changed to `[activityDetection, timeLapse]`
- [x] `taxonID` is removed from the observations table. This affects building the taxonomic scope from the data (#2132). 
  - [x] The taxonomic scope should now be built from the unique `scientificName` in the observations (not the combination of `taxonID` and `scientificName`.
  - [x] Taxa in a generated taxonomic scope will then only contain the property `scientificName`, which is fine. `taxonID` is no longer a required property (specifically to allow building a scope from the data).
  - [x] Taxa in the taxonomic scope now longer have a property `taxonIDReference`. This requires no change to the IPT: it would only get in there when uploading a non-1.0 `datapackage.json` (which is fine). I assume #2131 treats the taxonomic scope _as is_ when uploading?
- [x] None of the metadata terms have updated descriptions (except `taxonID`), so that does not affect the help text in the metadata editor. I did notice some minor issues that are best corrected:
  - [x] `Basic metadata > Title`: end description with `.` (consistency across terms)
  - [x] `Basic metadata > Contributor > Title`: end description with `.`
  - [x] `Basic metadata > Contributor > Path`: end description with `.`
  - [x] `Basic metadata > Contributor > Email`: end description with `.`
  - [x] `Basic metadata > Sources > Title`: end description with `.`
  - [x] `Basic metadata > Sources > Email`: end description with `.`
  - [x] `Basic metadata > Sources > Version`: end description with `.`
  - [x] `Basic metadata > Data license`: License for the content of the package and resources. The `name` MUST be an [Open Definition license ID](http://licenses.opendefinition.org/). #2186 
  - [x] `Basic metadata > Media license`: License for the (locally or externally hosted) media files referenced in `media.filePath`. The `name` MUST be an [Open Definition license ID](http://licenses.opendefinition.org/). #2186 
  - [x] `Taxonomic Scope > TaxonID`: [taxonID](https://camtrap-dp.tdwg.org/metadata/#taxonomic.taxonID) has an updated definition, but no help text appears for this term in the IPT
- [x] New website URL https://camtrap-dp.tdwg.org/ (instead of https://tdwg.github.io/camtrap-dp). While the old URL will redirect, it would be best to update all references.
- [x] Remove support for the release candidate of Camtrap DP (1.0-rc.1): this version was never included in a production version of the IPT and would only be confusing for users.
- [x] I wonder if the IPT should warn if users upload a `datapackage.json` that refers to an older version of Camtrap DP? See separate issue #2184

**Comment by mike-podolskiy90** [comment]
Great  news!

**Comment by mike-podolskiy90** [comment]
> I assume https://github.com/gbif/ipt/issues/2131 treats the taxonomic scope as is when uploading?

Correct

> I wonder if the IPT should warn if users upload a datapackage.json that refers to an older version of Camtrap DP?

Yes, I think so.

**Comment by peterdesmet** [comment]
What Camtrap DP version was used can be discerned from the `profile` property of an uploaded datapackage.json:

    "profile": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/camtrap-dp-profile.json"
    
The IPT should warn if:

- `profile` property is missing
- `<version>` string cannot be found
- `<version>` is different from the one supported by IPT.

Suggested warning:

> The uploaded datapackage.json references a Camtrap DP version (unknown) not supported by this IPT (1.0). Some terms might not be mapped correctly.
> 
> Continue / Cancel

**Comment by mike-podolskiy90** [comment]
Thanks Peter. Let's create a dedicated issue for that

**Comment by mike-podolskiy90** [comment]
@peterdesmet 
Having issues with fields `bboxWidth` and `bboxHeight`. This value `1e-15` is the problem. Do we really need to validate such a small thing? Why the `minimum` constraint was introduced?

Currently `minimum` and `maximum` constraints are integer numbers, so do we need to change that?

**Comment by peterdesmet** [comment]
Can you clarify what the issue is? `1e-15` is the scientific notation for 0.000000000000001, which is used here to express >0 (higher but not equal to 0).

> Currently `minimum` and `maximum` constraints are integer numbers, so do we need to change that? 

Where is that expressed? `1e-15` for example is not an integer number. And even if they would be integer numbers (like in [bboxX](https://camtrap-dp.tdwg.org/data/#observations.bboxX)), it is the data type of the field that matters.

**Comment by mike-podolskiy90** [comment]
All the minimun and maximum constraints used to be integers, so I assumed it's integer.
https://github.com/gbif/ipt/blob/master-ipt-3-frictionless/src/main/java/org/gbif/ipt/model/DataSchemaFieldConstraints.java#L35

**Comment by mike-podolskiy90** [comment]
`Number` class seems working fine, so I'll use that

**Comment by mike-podolskiy90** [comment]
@peterdesmet Deployed to UAT. I'll keep the 1.0-rc.1 schema for testing purposes and remove it when we're ready to release.

**Comment by peterdesmet** [comment]
I notice that published datasets refer to:

> https://rs.gbif.org/sandbox/experimental/camtrap-dp/1.0-rc.1/profile/camtrap-dp-profile.json

That should be updated to 1.0

**Comment by mike-podolskiy90** [comment]
Thanks Peter. I've just noticed that too. Issue #2191
